name: Build and Test Module Updates in Brand Plugins
on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

  bluehost:
    name: Bluehost Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@add/secondary-module-inputs
    with:
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: 'bluehost/bluehost-wordpress-plugin'
      secondary-module-repo: 'newfold-labs/wp-module-onboarding'
      secondary-module-branch: 'enhance/ai-onboarding'
    secrets: inherit

  hostgator:
    name: HostGator Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@add/secondary-module-inputs
    with:
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: 'newfold-labs/wp-plugin-hostgator'
      secondary-module-repo: 'newfold-labs/wp-module-ecommerce'
      secondary-module-branch: 'main'
    secrets: inherit

  web:
    name: Web.com Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@add/secondary-module-inputs
    with:
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: 'newfold-labs/wp-plugin-web'
      secondary-module-repo: 'newfold-labs/wp-module-data'
    secrets: inherit

  crazydomains:
    name: Crazy Domains Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@add/secondary-module-inputs
    with:
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: 'newfold-labs/wp-plugin-crazy-domains'
      secondary-module-branch: 'expect-to-be-skipped'
    secrets: inherit

  mojo:
    name: Mojo Build and Test
    needs: setup
    uses: newfold-labs/workflows/.github/workflows/module-plugin-test.yml@add/secondary-module-inputs
    with:
      module-repo: ${{ github.repository }}
      module-branch: ${{ needs.setup.outputs.branch }}
      plugin-repo: 'newfold-labs/wp-plugin-mojo'
      secondary-module-repo: 'newfold-labs/wp-module-data'
      secondary-module-branch: 'expect-to-fail'
    secrets: inherit
