name: PHP Lint
on:
  push:
    branches:
      - '**'
    paths:
      - '**.php'
  pull_request:
    types: [ opened, edited, reopened, ready_for_review ]
    paths:
      - '**.php'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  php-lint:
    name: PHP Lint
    uses: newfold-labs/workflows/.github/workflows/reusable-php-lint.yml@b650944ae6f4366237bc230a00dd3e18d99b2655
    with:
      php-version: '8.1'
      pr-base-sha: ${{ github.event.pull_request.base.sha }}
      pr-head-sha: ${{ github.event.pull_request.head.sha }}
