name: Workflow Lint
on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
    branches:
      - main
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  lint:
    name: Lint Workflows
    uses: newfold-labs/workflows/.github/workflows/reusable-workflow-lint.yml@main
    secrets: inherit
